## Tensorflow Denemeleri

Geçtiğimiz haftanın büyük bir bölümünde, Derin Öğrenme modellerinizde tensörler kullandınız. Bugünkü zorluklar boyunca, tensörleri kapsamlı bir şekilde kullanacak ve bazı alışılmadık model mimarileriyle çalışacaksınız.


Bu ısınma çalışmasında, bazı yeni yöntemlerle tanışacaksınız.

Buradaki tüm yöntemler, günün ilerleyen saatlerinde karşılaşacağınız zorlukları 100 kat daha kolay hale getirecek, bu nedenle daha sonra takılırsanız, doğru cevapları nasıl bulduğunuzu görmek için buraya geri dönün.

In [1]:
import tensorflow as tf

A) `tf.ones` kullanarak (3,3) şeklinde birler ile doldurulmuş bir tensör `a` oluşturun.

In [23]:
a = tf.ones((3, 3))
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

B) tf.expand_dims kullanarak `a`'yı `b` adlı (1,3,3) şekilli bir nesne haline getirin.

In [24]:
b = tf.expand_dims(a, axis=0)
b

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

C) Boyutu (9,1) olan ve sıfırlarla dolu bir tensör `c` oluşturun.

In [25]:
c = tf.zeros((9, 1))
c

<tf.Tensor: shape=(9, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

D) `c`'yi (1, 3, 3) şeklinde yeniden şekillendirin. Adını `d` olarak belirleyin.

In [26]:
d = tf.reshape(c, (1, 3, 3), name="d")
d

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

E) `tf.matmul` kullanarak `b` ve `d` matrislerini birbiriyle çarpın ve şimdi tensörü `e`'ye atayın.

In [27]:
e = tf.matmul(b, d)
e

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

F) Aşağıda bir `numpy` dizisi bulunmaktadır. Bunu `array_tensor` adlı bir tensöre dönüştürün. Ardından `tf.cast` kullanarak bunun `int` değil `float` türü olduğundan emin olun. Sonucu `f`'ye atayın.

In [7]:
import numpy as np

In [8]:
array = np.array([[
    [1,2,3],
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])

In [28]:
array_tensor = tf.convert_to_tensor(array)
f = tf.cast(array_tensor, dtype=tf.float32)
f

<tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]], dtype=float32)>

G) `f`'nin __last column__ değerleri seçin ve bunu `g`'ye kaydedin. Açıkça belirtmek gerekirse, `g`'nin şekli (4,) olmalı ve `3,3,6,9` değerlerini içermelidir.

In [30]:
g = f[:, :, -1]
g

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[3., 3., 6., 9.]], dtype=float32)>

H) g boyutlarını (4,1) şekline gelecek şekilde genişletin. Bunu `h`'ye atayın.

In [31]:
h = tf.reshape(g, (4, 1))
h

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[3.],
       [3.],
       [6.],
       [9.]], dtype=float32)>

I) İsteğe bağlı `transpose_b` argümanıyla `tf.matmul` kullanarak e ile f'yi çarpın (konumsal argümanlarınızda önce `e`, sonra `f` gelmelidir). Bunu `i`'ye atayın.

In [32]:
i = tf.matmul(e, f, transpose_b=True)
i

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

J) Birlerle dolu bir `(10,10)` tensör oluşturun. Ardından `tf.linalg.band_part()` kullanarak matrisin üst üçgenini maskeleme yapın (yani üst üçgenin tamamı 0 olmalıdır). `j`'ye atayın.

In [33]:
j_full = tf.ones((10, 10))
j = tf.linalg.band_part(j_full, -1, 0)
j

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

K) Aşağıdaki `number_list`'i alın ve bir tensör haline getirin. Bunu `k`'ye atayın.

In [14]:
number_list = [1,2,3,4,8]

In [34]:
k = tf.convert_to_tensor(number_list)
k

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 8], dtype=int32)>

L) `tf.expand_dims` kullanarak `k`'yi (1,5) şekilli bir tensör haline getirin. `l`'ye atayın.

In [35]:
l = tf.expand_dims(k, axis=0)
l

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 2, 3, 4, 8]], dtype=int32)>

M) `tf.tile` kullanarak `l` (okunuşu “L”) 50 kez tekrarlayın, sonuçta `(50, 5)` şeklinde olsun. `m`'ye atayın.

In [36]:
m = tf.tile(l, [50, 1])
m

<tf.Tensor: shape=(50, 5), dtype=int32, numpy=
array([[1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 4, 8],
       [1, 2, 3, 

N) Basit bir Boolean ifadesi kullanarak, `m`'nin 3 olduğu yerler için `True` değerleri ve 3 olmadığı yerler için `False` değerleri içeren bir tensör oluşturun. `n`'ye atayın.

In [38]:
n = m == 3
n

<tf.Tensor: shape=(50, 5), dtype=bool, numpy=
array([[False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, F

O) Değişkeniniz `m` içindeki her değeri 3'e bölün. `o`'ya atayın.

In [39]:
o = m / 3
o

<tf.Tensor: shape=(50, 5), dtype=float64, numpy=
array([[0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 2.66666667],
       [0.33333333, 0.66666667, 1.        , 1.33333333

P) `tf.concat()` kullanarak, aşağıdaki (5,5) ve (5,5) şekilli iki tensörün listesini alın ve bunları (10,5) şekilli son bir tensöre dönüştürün. `p`'ye atayın. Birleştirme eksenini dikkatlice düşünün.

In [40]:
p = tf.concat(tensor_list, axis=0)
p

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [41]:
!pip install nbresult

### Cevaplarını Kontrol Et

In [43]:
result.write()
print(result.check())

result = ChallengeResult(
    "tensors",
    a=a.numpy(),
    b=b.numpy(),
    c=c.numpy(),
    d_shape=tuple(d.shape),
    e=e.numpy(),
    f=f.numpy(),
    g=g.numpy(),
    h=h.numpy(),
    i=i.numpy(),
    j=j.numpy(),
    k=k.numpy(),
    l=l.numpy(),
    m=m.numpy(),
    n=n.numpy(),
    o=o.numpy(),
    p_shape=tuple(p.shape),
)

result.write()
print(result.check())

NameError: Could not find /tests directory in any parent folder

### Harika iş 🔥

Şimdi modellemeye başlama zamanı!